---
downloads: ~/.ansible-downloads/

configure_dotfiles: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - Maps
  - FaceTime
  - Contacts
  - Freeform
  - TV
  - Music
  - News
  - "App Store"
  - Safari
dockitems_persist:
  - name: "Firefox Developer Edition"
    path: "/Applications/Firefox Developer Edition.app/"
    pos: 2
  - name: "Discord"
    path: "/Applications/Discord.app/"
    pos: 3
  - name: "Alacritty"
    path: "/Applications/Alacritty.app/"
    pos: 7
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 8
dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bat
  - cloudflare/cloudflare/cloudflared
  - fd
  - fnm
  - fzf
  - git
  - gnupg
  - go
  - helmfile
  - htop
  - jq
  - koekeishiya/formulae/skhd
  - koekeishiya/formulae/yabai
  - kube-ps1
  - kubectx
  - neovim
  - oven-sh/bun/bun
  - pinentry-mac
  - pyenv
  - ripgrep
  - sops
  - stow
  - tldr
  - tmux
  - wget
  - wireguard-tools
  - zsh-completions

homebrew_taps:
  - homebrew/cask-versions
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alacritty
  - discord
  - firefox-developer-edition
  - google-chrome
  - spotify
  - postman

npm_packages:
  - name: firebase-tools
    state: latest
  - name: yarn
    state: latest
  - name: npm-check-updates
    state: latest

fnm_nodejs_versions:
  - "18"
  - "20"

fnm_default_nodejs_version: "20"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

users:
  - username: sschiffli
    visual_studio_code_extensions:
      - Catppuccin.catppuccin-vsc
      - Catppuccin.catppuccin-vsc-icons
      - GitHub.copilot
      - GitHub.copilot-chat
      - streetsidesoftware.code-spell-checker
      - eamodio.gitlens
      - vscodevim.vim
      - esbenp.prettier-vscode
      - rust-lang.rust-analyzer
      - golang.Go
      - bradlc.vscode-tailwindcss

    visual_studio_code_settings_overwrite: true
    visual_studio_code_settings:
      {
        "editor.inlayHints.enabled": "off",
        "terminal.integrated.enableMultiLinePasteWarning": false,
        "editor.minimap.enabled": false,
        "editor.formatOnSave": true,
        "editor.inlineSuggest.enabled": true,
        "editor.lineNumbers": "relative",
        "editor.cursorSurroundingLines": 8,
        "github.copilot.enable":
          {
            "*": false,
            "plaintext": false,
            "markdown": true,
            "scminput": false,
            "yaml": true,
          },
        "[typescriptreact]":
          { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[javascript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[typescript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[json]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "[jsonc]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
        "editor.codeActionsOnSave": { "source.addMissingImports": true },
        "workbench.startupEditor": "none",
        "terminal.integrated.fontSize": 12,
        "editor.fontFamily": "'JetBrainsMono Nerd Font'",
        "editor.fontVariations": false,
        "editor.fontSize": 12,
        "git.confirmSync": false,
        "explorer.confirmDelete": false,
        "vim.leader": "<space>",
        "vim.hlsearch": false,
        "vim.incsearch": true,
        "vim.useSystemClipboard": true,
        "vim.highlightedyank.enable": true,
        "cSpell.userWords": ["dumbass", "firestore", "Leaderboard", "matchups"],
        "vim.visualModeKeyBindingsNonRecursive":
          [{ "before": ["<leader>", "p"], "after": ['"', "_", "d", "P"] }],
        "vim.normalModeKeyBindingsNonRecursive":
          [
            { "before": ["<C-d>"], "after": ["<C-d>", "z", "z"] },
            { "before": ["<C-u>"], "after": ["<C-u>", "z", "z"] },
            { "before": ["n"], "after": ["n", "z", "z", "z", "v"] },
            { "before": ["N"], "after": ["N", "z", "z", "z", "v"] },
          ],
        "editor.stickyScroll.enabled": true,
        "go.toolsManagement.autoUpdate": true,
        "workbench.iconTheme": "catppuccin-latte",
        "workbench.colorTheme": "Catppuccin Latte",
        "git.openRepositoryInParentFolders": "always",
      }
    visual_studio_code_keybindings_overwrite: true
    visual_studio_code_keybindings:
      [
        { "key": "ctrl+'", "command": "workbench.action.terminal.focus" },
        {
          "key": "ctrl+'",
          "command": "workbench.action.focusActiveEditorGroup",
          "when": "terminalFocus",
        },
        { "key": "ctrl+f", "command": "workbench.action.openRecent" },
        { "key": "ctrl+r", "command": "-workbench.action.openRecent" },
      ]
