---
downloads: ~/.ansible-downloads/

configure_dotfiles: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - Maps
  - FaceTime
  - Contacts
  - Freeform
  - TV
  - Music
  - News
  - "App Store"
  - Safari
dockitems_persist:
  - name: "Firefox Developer Edition"
    path: "/Applications/Firefox Developer Edition.app/"
    pos: 2
  - name: "Discord"
    path: "/Applications/Discord.app/"
    pos: 3
  - name: "Alacritty"
    path: "/Applications/Alacritty.app/"
    pos: 7
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 8
dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bat
  - cloudflare/cloudflare/cloudflared
  - fd
  - fnm
  - fzf
  - git
  - gnupg
  - go
  - helmfile
  - htop
  - jq
  - koekeishiya/formulae/skhd
  - koekeishiya/formulae/yabai
  - kube-ps1
  - kubectx
  - neovim
  - oven-sh/bun/bun
  - pinentry-mac
  - pyenv
  - ripgrep
  - sops
  - stow
  - tldr
  - tmux
  - wget
  - wireguard-tools
  - zsh-completions

homebrew_taps:
  - homebrew/cask-versions
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alacritty
  - visual-studio-code
  - discord
  - firefox-developer-edition
  - google-chrome
  - spotify
  - postman

npm_packages:
  - name: firebase-tools
    state: latest
  - name: yarn
    state: latest
  - name: npm-check-updates
    state: latest

fnm_nodejs_versions:
  - "18"
  - "20"

fnm_default_nodejs_version: "20"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
