---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]
    - role: gantsign.visual-studio-code
      users:
        - username: sschiffli
          visual_studio_code_extensions:
            - Catppuccin.catppuccin-vsc
            - Catppuccin.catppuccin-vsc-icons
            - streetsidesoftware.code-spell-checker
            - eamodio.gitlens
            - vscodevim.vim
            - esbenp.prettier-vscode
            - rust-lang.rust-analyzer
            - golang.Go
            - bradlc.vscode-tailwindcss

          visual_studio_code_settings_overwrite: true
          visual_studio_code_settings:
            {
              "editor.inlayHints.enabled": "off",
              "terminal.integrated.enableMultiLinePasteWarning": false,
              "editor.minimap.enabled": false,
              "editor.formatOnSave": true,
              "editor.inlineSuggest.enabled": true,
              "editor.lineNumbers": "relative",
              "editor.cursorSurroundingLines": 8,
              "github.copilot.enable":
                {
                  "*": false,
                  "plaintext": false,
                  "markdown": true,
                  "scminput": false,
                  "yaml": true,
                },
              "[typescriptreact]":
                { "editor.defaultFormatter": "esbenp.prettier-vscode" },
              "[javascript]":
                { "editor.defaultFormatter": "esbenp.prettier-vscode" },
              "[typescript]":
                { "editor.defaultFormatter": "esbenp.prettier-vscode" },
              "[json]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
              "[jsonc]":
                { "editor.defaultFormatter": "esbenp.prettier-vscode" },
              "editor.codeActionsOnSave": { "source.addMissingImports": true },
              "workbench.startupEditor": "none",
              "terminal.integrated.fontSize": 12,
              "editor.fontFamily": "'JetBrainsMono Nerd Font'",
              "editor.fontVariations": false,
              "editor.fontSize": 12,
              "git.confirmSync": false,
              "explorer.confirmDelete": false,
              "vim.leader": "<space>",
              "vim.hlsearch": false,
              "vim.incsearch": true,
              "vim.useSystemClipboard": true,
              "vim.highlightedyank.enable": true,
              "cSpell.userWords":
                ["dumbass", "firestore", "Leaderboard", "matchups"],
              "vim.visualModeKeyBindingsNonRecursive":
                [
                  {
                    "before": ["<leader>", "p"],
                    "after": ['"', "_", "d", "P"],
                  },
                ],
              "vim.normalModeKeyBindingsNonRecursive":
                [
                  { "before": ["<C-d>"], "after": ["<C-d>", "z", "z"] },
                  { "before": ["<C-u>"], "after": ["<C-u>", "z", "z"] },
                  { "before": ["n"], "after": ["n", "z", "z", "z", "v"] },
                  { "before": ["N"], "after": ["N", "z", "z", "z", "v"] },
                ],
              "editor.stickyScroll.enabled": true,
              "go.toolsManagement.autoUpdate": true,
              "workbench.iconTheme": "catppuccin-latte",
              "workbench.colorTheme": "Catppuccin Latte",
              "git.openRepositoryInParentFolders": "always",
            }
          visual_studio_code_keybindings_overwrite: true
          visual_studio_code_keybindings:
            [
              { "key": "ctrl+'", "command": "workbench.action.terminal.focus" },
              {
                "key": "ctrl+'",
                "command": "workbench.action.focusActiveEditorGroup",
                "when": "terminalFocus",
              },
              { "key": "ctrl+f", "command": "workbench.action.openRecent" },
              { "key": "ctrl+r", "command": "-workbench.action.openRecent" },
            ]
      tags: ["vscode"]
  tasks:
    - import_tasks: tasks/mac.yml
      tags: ["mac"]
    - import_tasks: tasks/git.yml
      tags: ["git"]
    - import_tasks: tasks/rustup.yml
      tags: ["rustup"]
    - import_tasks: tasks/term.yml
      tags: ["term"]
    - import_tasks: tasks/tmux.yml
      tags: ["tmux"]
    - import_tasks: tasks/zsh.yml
      tags: ["zsh"]
    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]
    - import_tasks: tasks/fnm-node.yml
      tags: ["fnm"]

    - name: Run post-provision task files in a block.
      tags: ["post"]
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
