---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]
    - role: gantsign.visual-studio-code
      tags: ["vscode"]
  tasks:
    - import_tasks: tasks/mac.yml
      tags: ["mac"]
    - import_tasks: tasks/rustup.yml
      tags: ["rustup"]
    - import_tasks: tasks/term.yml
      tags: ["term"]
    - import_tasks: tasks/tmux.yml
      tags: ["tmux"]
    - import_tasks: tasks/zsh.yml
      tags: ["zsh"]
    - import_tasks: tasks/fnm-node.yml
      tags: ["fnm"]
    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]
    - name: Run post-provision task files in a block.
      tags: ["post"]
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
