---
- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: sschiffli@gmail.com
  tags:
  - git
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: Stephen Schiffli
  tags:
  - git
- name: Git personal setup signingkey
  git_config:
    name: user.signingkey
    scope: global
    value: E4179C77C7B431D11E8EDD352679C1ED9835DB48
  tags:
  - git
- name: Git setup sign commits
  git_config:
    name: commit.gpgsign
    scope: global
    value: true
  tags:
  - git
- name: Git setup sign tags
  git_config:
    name: tag.gpgsign
    scope: global
    value: true
  tags:
  - git
- name: Git setup default main
  git_config:
    name: init.defaultBranch
    scope: global
    value: main
  tags:
  - git
- name: Git setup auto setup remote
  git_config:
    name: push.autoSetupRemote
    scope: global
    value: true
  tags:
  - git
- name: Git setup pull ff only
  git_config:
    name: pull.ff
    scope: global
    value: only
  tags:
  - git