- name: Pull in rustup
  become_user: sschiffli
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path -c rust-analyzer
  tags: ["rustup"]
  args:
    creates: ~/.rustup
